apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlp

resources:
  - deployment.yaml
  - service.yaml

labels:
  - includeSelectors: false   # the Deployment selector is immutable once created
    includeTemplates: true
    pairs:
      app.kubernetes.io/managed-by: argocd
