apiVersion: v1
kind: Service
metadata:
  name: sink
  labels:
    app.kubernetes.io/name: sink
    app.kubernetes.io/part-of: my-local-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sink
  ports:
    - name: http
      port: 8081
      targetPort: http
