apiVersion: v1
kind: ServiceAccount
metadata:
  name: relay-ingest
  labels:
    app.kubernetes.io/part-of: my-local-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: relay-deliver
  labels:
    app.kubernetes.io/part-of: my-local-platform
