#!/usr/bin/env bash
# Regenerate the in-cluster dashboard ConfigMap from the compose dashboard.
#
# There is ONE dashboard definition in this repository:
#
#   local/config/grafana/provisioning/dashboards/relay.json
#
# The compose Grafana reads it as a file. The in-cluster Grafana cannot -- it
# collects ConfigMaps labelled `grafana_dashboard: "1"`, which its sidecar
# watches across every namespace. So the JSON has to appear in a ConfigMap too,
# and the only question is how to stop the two drifting.
#
# Generating it here rather than with kustomize's configMapGenerator, because
# that would need to read a file outside the kustomization root and kustomize
# refuses by default -- it would take a symlink or ArgoCD configured with
# LoadRestrictionsNone, which is more moving parts than a script and a test.
#
# The generated file is COMMITTED, so ArgoCD syncs plain YAML with no build
# step, and TestDashboardConfigMapMatchesTheSourceFile in k8s/validate fails if
# someone edits relay.json and forgets to run this.
#
#   ./scripts/gen-dashboard-configmap.sh     # or: make monitoring-dashboard
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source_json="$repo_root/local/config/grafana/provisioning/dashboards/relay.json"
output="$repo_root/k8s/manifests/monitoring/dashboard-relay.yaml"

if [ ! -f "$source_json" ]; then
  echo "no dashboard at $source_json" >&2
  exit 1
fi

# Reject invalid JSON here rather than shipping a ConfigMap whose payload
# Grafana silently refuses to load.
if ! python3 -c "import json,sys; json.load(open(sys.argv[1]))" "$source_json"; then
  echo "$source_json is not valid JSON" >&2
  exit 1
fi

python3 - "$source_json" "$output" <<'PY'
import sys

source, output = sys.argv[1], sys.argv[2]
with open(source) as f:
    dashboard = f.read()

header = """# GENERATED by scripts/gen-dashboard-configmap.sh -- do not edit.
#
# The dashboard itself lives at
# local/config/grafana/provisioning/dashboards/relay.json, which the compose
# Grafana reads directly. Edit that file and re-run the script, or
# `make monitoring-dashboard`. k8s/validate fails when the two disagree.
#
# The `grafana_dashboard: "1"` label is what the chart's Grafana sidecar
# watches for; it runs with NAMESPACE: ALL, so this ConfigMap is collected from
# the mlp namespace by a Grafana running in monitoring.
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-relay
  labels:
    grafana_dashboard: "1"
    app.kubernetes.io/part-of: my-local-platform
data:
  relay.json: |
"""

# Six spaces: four for the block scalar under `data.relay.json`, matching the
# two-space YAML indent used everywhere else here. Blank lines stay empty
# rather than becoming whitespace-only, which some YAML parsers treat as
# significant.
body = "".join(
    ("      " + line if line.strip() else "") + "\n"
    for line in dashboard.splitlines()
)

with open(output, "w") as f:
    f.write(header)
    f.write(body)
PY

echo "wrote $output from $source_json"
