apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: mlp

  source:
    repoURL: __REPO_URL__
    targetRevision: main
    path: k8s/manifests/echo

  destination:
    server: https://kubernetes.default.svc
    namespace: mlp

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
