apiVersion: v1
kind: Service
metadata:
  name: relay-ingest
  labels:
    app.kubernetes.io/name: relay-ingest
    app.kubernetes.io/part-of: my-local-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: relay-ingest
  ports:
    - name: http
      port: 80
      targetPort: http
